config/routes.rb
Rails.application.routes.draw do
  root to: proc { [200, {}, ['Alive']] }

  match '/auth/:provider/callback'        => 'omniauth#callback',    as: :omniauth_callback, via: [:get, :post]
  get   '/auth/failure'                   => 'omniauth#failure',     as: :omniauth_failure

  # Entry point for the Zebra splash pages.
  # "organization" - the unique identifier given to the client company.
  # "page_path" - the hierachical path to the unique splash page
  get    '/splash/aruba/:organization/*page_path'  => 'splash/aruba#index',                as: :aruba_splash
  get    '/splash/meraki/sms/:organization/*page_path' => 'splash/verification/sms#index', as: :meraki_splash_sms
  post   '/splash/meraki/sms/register'                 => 'splash/verification/sms#register', as: :meraki_sms_registration
  post   '/splash/meraki/sms/verify'                   => 'splash/verification/sms#verify_code', as: :meraki_sms_verification
  get    '/splash/meraki/:organization/*page_path' => 'splash/meraki#index',               as: :meraki_splash


  get    '/splash/sponsor/22carnot/sponsor'           => 'splash/carnot_sponsor#sponsor',                 as: :carnot_sponsor_splash
  post   '/splash/sponsor/22carnot/register'          => 'splash/carnot_sponsor#register',                as: :carnot_sponsor_registration
  get    '/splash/sponsor/22carnot/wait'              => 'splash/carnot_sponsor#wait',                    as: :carnot_sponsor_wait
  get    '/splash/sponsor/22carnot/verify/:key'       => 'splash/carnot_sponsor#check_verification',      as: :carnot_sponsor_wait_verification
  get    '/splash/sponsor/22carnot/code'              => 'splash/carnot_sponsor#access_code',             as: :carnot_access_code
  post   '/splash/sponsor/22carnot/code_verification' => 'splash/carnot_sponsor#verify_code',             as: :carnot_access_code_verification
  get    '/splash/sponsor/22carnot/authorize/:key'    => 'splash/carnot_sponsor#authorize_registration', as: :carnot_sponsor_authorization

  get    '/splash/sponsor/ftp/sponsor'           => 'splash/ftp_sponsor#sponsor',                 as: :ftp_sponsor_splash
  post   '/splash/sponsor/ftp/register'          => 'splash/ftp_sponsor#register',                as: :ftp_sponsor_registration
  get    '/splash/sponsor/ftp/wait'              => 'splash/ftp_sponsor#wait',                    as: :ftp_sponsor_wait
  get    '/splash/sponsor/ftp/verify/:key'       => 'splash/ftp_sponsor#check_verification',      as: :ftp_sponsor_wait_verification
  get    '/splash/sponsor/ftp/code'              => 'splash/ftp_sponsor#access_code',             as: :ftp_access_code
  post   '/splash/sponsor/ftp/code_verification' => 'splash/ftp_sponsor#verify_code',             as: :ftp_access_code_verification
  get    '/splash/sponsor/ftp/authorize/:key'    => 'splash/ftp_sponsor#authorization_duration', as: :ftp_sponsor_authorization
  post   '/splash/sponsor/ftp/authorize/:key'    => 'splash/ftp_sponsor#authorize_registration', as: :ftp_sponsor_authorize

  get    '/splash/pages/*template_path'            => 'splash#template_path',              as: :page_template
  get    '/splash/:organization/(:page)'           => 'splash#index',                      as: :splash
  get    '/page/*path'                             => 'splash#page',                       as: :page
  get    '/external/authorize'                     => 'splash/external_splash#authorize',  as: :external_authorize
  get    '/external/:organization/(:page)'         => 'splash/external_splash#redirect',   as: :external_splash
  post   '/registration/(:type)'                   => 'splash/registration#register',      as: :registration
  get    '/finished'                               => 'splash/post_authorization#index',   as: :post_authorization

  get    '/optout'                                 => 'splash#authorize',                  as: :optout
  get    '/aruba/authorize'                        => 'splash/aruba#authorize',            as: :aruba_authorization

  get    '/alive'                                  => 'splash#alive',                      as: :health_check
  get    '/parameters'                             => 'internal#debug',                    as: :parameter_debug

  # Client specific
  post '/email_registration'                       => 'splash/email_registration#register',   as: :email_registration

end

app/views/splash/pages/templates/facebook.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="user-scalable=1.0,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0">

    <title><%= organization.capitalize %></title>
    <link rel="stylesheet" href="/assets/custom/shared/stylesheets/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/custom/shared/stylesheets/background.css">
    <link rel="stylesheet" href="/assets/custom/shared/tooltips.css">
    <script type="text/javascript" src="/assets/custom/shared/javascript/jquery/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/assets/custom/shared/javascript/jquery/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/assets/custom/shared/parsley.min.js"></script>
    <script type="text/javascript" src="/assets/custom/shared/javascript/cgu.js"></script>
    <style type="text/css" media="screen">
      .parsley-error {
        color: #B94A48 !important;
        background-color: #F2DEDE !important;
        border: 1px solid #EED3D7 !important;
      }
      .form-input {
        padding-bottom: 3px;
      }
      .text-wifi {
        font-size: 16px;
        color: black;
      }

      #link_cgu, .text-cgu {
        color: black;
      }
    </style>
  </head>
  <body>
    <div id="background_image"></div><!-- End Background -->

    <div id="header">
      <%%= image_tag  asset_data_uri('<%= logo_path %>'), class: 'img-responsive', id: 'header_logo' %>
    </div>

    <div class="row">
      <div class="col-lg-12 text-center">
        <p class="text-wifi"><%%= t('form.instructions') %>
        <br><%%= t('splash.facebook.or') %> <%%= link_to t('splash.facebook.alternative'), alt_page('registration') %>
    </p>
    <%%= render 'splash/facebook_login' %>
  </div>

  <div id="MMD_conditions">
    <div id="MMD_conditionsHeader">
      <div class="MMD_conditionsTitre MMD_F1">Conditions Générales de Utilisation</div>
      <img id="MMD_conditionsCClick" class="MMD_conditionsClose" src="/assets/custom/shared/images/Close_btn.png" />
    </div>
    <div class="container">
      <div class="row">
        <div class="MMD_innerContent">
          <div class="MMD_conditionsTexte MMD_F1">
            <%%= render 'splash/ivizone_terms.fr' %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%%= render 'splash/international_phone_formatter' %>
</body>
</html>

app/views/splash/pages/templates/facebook.html.haml.erb
:css
  #logo {
    height: <%= logo_height %>px;
    width: <%= logo_width %>px;
    margin-top: 40px;
  }

  .terms-link {
    position: relative;
    top: -40px;
  }

  .welcome-message {
    margin-bottom: 20px;
  }

.welcome
  .row
    = image_tag  asset_data_uri('<%= logo_path %>'), class: 'img-responsive', id: 'logo'

  .row.welcome-message
    %p#message
      = t('splash.facebook.instructions')
      %br #{t('splash.facebook.or')} #{link_to t('splash.facebook.alternative'), alt_page('registration') }

  = render 'splash/facebook_login'

  .row.center-text.terms-link
    = render 'terms_link'

app/views/splash/pages/templates/registration.html.haml.erb
:css
  #logo {
    height: <%= logo_height %>px;
    width: <%= logo_width %>px;
    margin-top: 40px;
  }

  .submit-btn {
    margin-top: 10px;
    font-weight: 700;
    width: 100%;
    background-color: <%= registration_button_color %>;
    color: white;
  }

:css
  .ivizone-form {
    width: 80%;
    margin: auto;
    margin-bottom: 20px;
  }

  .form-group {
    margin: 0;
    margin-bottom: 8px;
  }

  .parsley-error {
    color: #B94A48 !important;
    background-color: #F2DEDE !important;
    border: 1px solid #EED3D7 !important;
  }


  .cgu label:after {
    color: black;
  }

.welcome
  .row
    = image_tag  asset_data_uri('<%= logo_path %>'), class: 'img-responsive', id: 'logo'

  .row.welcome-message
    %p#message
      = t('form.instructions')
      %br #{t('form.or')} #{link_to t('form.facebook_alternative'), alt_page('facebook') }

  = form_tag registration_path, class: 'ivizone-form', role: 'form', id: 'ivizone-form', data: {'parsley-validate': true, 'parsley-focus': 'none'} do
    <% if show_fields[:name] %>
    .form-group
      = label_tag 'last_name', t('form.labels.last_name')
      = text_field_tag 'last_name', nil, placeholder: t('form.placeholder.last_name'), class: 'form-control', data: {'parsley-errors-messages-disabled': true, 'parsley-required': true}

    .form-group
      = label_tag 'first_name', t('form.labels.first_name')
      = text_field_tag 'first_name', nil, placeholder: t('form.placeholder.first_name'), class: 'form-control', data: {'parsley-errors-messages-disabled': true, 'parsley-required': true}
    <% end %>

    <% if show_fields[:phone] %>
    .form-group
      = label_tag 'phone', t('form.labels.phone')
      = phone_field_tag 'phone', nil, placeholder: t('form.placeholder.phone'), class: 'form-control', data: {'parsley-errors-messages-disabled': true, 'parsley-required': true}
    <% end %>

    <% if show_fields[:email] %>
    .form-group
      = label_tag 'email', t('form.labels.email')
      = email_field_tag 'email', nil, placeholder: t('form.placeholder.email'), class: 'form-control', data: {'parsley-errors-messages-disabled': true, 'parsley-required': true}
    <% end %>

    .form-group
      = check_box_tag 'cgu', nil, false, data: {'parsley-errors-messages-disabled': true, 'parsley-required': true}
      = label_tag 'cgu', t('legal.full_disclaimer')
      #{link_to t('legal.conditions'), '#', :'data-toggle' => "modal", id: 'termsLink', class: 'loader', :'data-target' => '#termsModal'}

    = render 'splash/default_splash_fields'

    = button_tag t('form.submit'), class: 'btn submit-btn', id: 'form-submit'

  .row.center-text.terms-link
    = render 'splash/terms_link'

= render 'splash/international_phone_formatter'

app/views/splash/pages/templates/sms_code.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="user-scalable=1.0,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0">

    <title><%= organization.capitalize %></title>
    <link rel="stylesheet" href="/assets/custom/shared/stylesheets/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/custom/shared/stylesheets/background.css">
    <link rel="stylesheet" href="/assets/custom/shared/tooltips.css">
    <script type="text/javascript" src="/assets/custom/shared/javascript/jquery/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/assets/custom/shared/javascript/jquery/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/assets/custom/shared/parsley.min.js"></script>
    <script type="text/javascript" src="/assets/custom/shared/javascript/cgu.js"></script>
    <style type="text/css" media="screen">
      .parsley-error {
        color: #B94A48 !important;
        background-color: #F2DEDE !important;
        border: 1px solid #EED3D7 !important;
      }
      .form-input {
        padding-bottom: 3px;
      }
      .text-wifi {
        font-size: 16px;
        color: black;
      }

      #link_cgu, .text-cgu {
        color: black;
      }

      #custom_sms {
        text-align: center;
      }
    </style>
  </head>
  <body>
    <div id="background_image"></div><!-- End Background -->

    <div id="header">
      <%%= image_tag  asset_data_uri('<%= logo_path %>'), class: 'img-responsive', id: 'header_logo' %>
    </div>


    <form action="<%%= meraki_sms_verification_path %>" id="ivizone-form" method="POST" data-parsley-validate="true">
      <div id="container">
        <div class="container">
          <div class="row">
            <div class="col-xs-12 form-input" id="error-phone">
              <input data-parsley-errors-messages-disabled type="tel" name="custom[sms]" id="custom_sms" class="form_MMD_F1" placeholder="<%%= t('sms.form.placeholder.code') %>"  required="" data-parsley-required="true" />
            </div>

            <%% if @invalid_code %>
            <p class='text-wifi-error'>
              <%%= t('sms.sms_invalid') %>
            </p>
            <%% end %>

            <%%= render 'splash/default_splash_fields' %>
            <div class="clearfix"></div>

            <div class="col-xs-10 col-xs-offset-1">
              <input id="MMD_formBtn" type="submit" class="MMD_F1" value="<%%= t('sms.form.validate') %>" />
            </div>

          </div>
          <br />
          <br />
          <div class='row text-wifi'>
            <%%= link_to t('sms.sms_new'), meraki_link("<%= sms_registration_path %>") %>
          </div>
        </div>
      </div>
    </form>
  </body>
</html>

app/views/splash/pages/templates/sms_code.html.haml.erb
!!! 5
%html(lang='#{I18n.locale}')
  %head
    = render 'shared/head'
  %body
    = stylesheet_link_tag 'application.css'
    = render 'splash/css/application'
    #spinner

    %div#main_content
      .container
        :css
          #logo {
            height: <%= logo_height %>px;
            width: <%= logo_width %>px;
            margin-top: 40px;
          }

          .submit-btn {
            margin-top: 10px;
            font-weight: 700;
            width: 100%;
            background-color: <%= registration_button_color %>;
            color: white;
          }

          .intl-tel-input {
              width: 100%;
              margin-top: 10px;
          }

        :css
          .ivizone-form {
            width: 80%;
            margin: auto;
            margin-bottom: 20px;
          }

          .form-group {
            margin: 0;
            margin-bottom: 8px;
          }

          .parsley-error {
            color: #B94A48 !important;
            background-color: #F2DEDE !important;
            border: 1px solid #EED3D7 !important;
          }

        .welcome
          .row
            = image_tag  asset_data_uri('<%= logo_path %>'), class: 'img-responsive', id: 'logo'

          .row.welcome-message
            %p#message

          = form_tag meraki_sms_verification_path, class: 'ivizone-form', role: 'form', id: 'ivizone-form', data: {'parsley-validate': true, 'parsley-focus': 'none'} do
            .form-group
              = phone_field_tag 'custom[sms]', nil, placeholder: t('sms.form.placeholder.code'), class: 'form-control', data: {'parsley-errors-messages-disabled': true, 'parsley-required': 'true'}
              - if @invalid_code
                %p(class="text-wifi-error")
                  = t('sms.sms_invalid') 

              = render 'splash/default_splash_fields'
              = button_tag t('sms.form.validate'), class: 'btn submit-btn', id: 'form-submit'

          .row.center-text.terms-link
            = link_to t('sms.sms_new'), meraki_link("<%= sms_registration_path %>")
            = javascript_include_tag 'application.js'
            = content_for :custom_javascript


    :javascript
      var opts = {
        lines: 10, // The number of lines to draw
        length: 13, // The length of each line
        width: 6, // The line thickness
        radius: 10, // The radius of the inner circle
        corners: 1, // Corner roundness (0..1)
        rotate: 0, // The rotation offset
        direction: 1, // 1: clockwise, -1: counterclockwise
        color: '#fff', // #rgb or #rrggbb or array of colors
        speed: 1.5, // Rounds per second
        trail: 30, // Afterglow percentage
        shadow: false, // Whether to render a shadow
        hwaccel: false, // Whether to use hardware acceleration
        className: 'spinner', // The CSS class to assign to the spinner
        zIndex: 2e9, // The z-index (defaults to 2000000000)
        top: '50', // Top position relative to parent in px
        left: '50' // Left position relative to parent in px
      };

      target = document.getElementById('spinner');
      var spinner = new Spinner(opts).spin(target);

      $('#facebook-link').click(function(e){
        $('#spinner').show();
        mixpanel.track('Facebook clicked');
      });

      if (typeof(Parsley) !== "undefined") {
        Parsley.on('form:submit', function(event){
          $('#spinner').show();
          mixpanel.track('Standard Form Submitted');
          //Ivizone.logEvent({event: 'UserSubmittedForm'});
        });
      }

      mixpanel.register(#{@tracking_data.to_json.html_safe});
      mixpanel.track("Page loaded");
      mixpanel.track_links('#termsLink', "Viewed Terms");

app/views/splash/pages/templates/sms_registration.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="user-scalable=1.0,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0">

    <title><%= organization.capitalize %></title>
    <link rel="stylesheet" href="/assets/custom/shared/stylesheets/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/custom/shared/stylesheets/background.css">
    <link rel="stylesheet" href="/assets/custom/shared/tooltips.css">
    <link rel="stylesheet" href="/assets/custom/shared/stylesheets/intlTelInput.css">
    <script type="text/javascript" src="/assets/custom/shared/javascript/jquery/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/assets/custom/shared/javascript/jquery/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/assets/custom/shared/parsley.min.js"></script>
    <script type="text/javascript" src="/assets/custom/shared/javascript/cgu.js"></script>
    <style type="text/css" media="screen">
      .parsley-error {
        color: #B94A48 !important;
        background-color: #F2DEDE !important;
        border: 1px solid #EED3D7 !important;
      }
      .form-input {
        padding-bottom: 3px;
      }
      .text-wifi {
        font-size: 16px;
        color: black;
      }

      #link_cgu, .text-cgu {
        color: black;
      }

      .intl-tel-input {
        /* width: 100%; */
      }
    </style>
  </head>
  <body>
    <div id="background_image"></div><!-- End Background -->

    <div id="header">
      <%%= image_tag  asset_data_uri('<%= logo_path %>'), class: 'img-responsive', id: 'header_logo' %>
    </div>

    <form action="<%%= meraki_sms_registration_path %>" id="ivizone-form" method="POST" data-parsley-validate="">
      <div id="container">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 text-center">
              <p class="text-wifi">
                <%%= t('form.instructions') %>
                <br><%%= t('form.or') %> <%%= link_to t('form.facebook_alternative'), alt_page('facebook') %>
              </p>

              <% if show_fields[:name] %>
                <div class="col-xs-12 form-input" id="error-first">
                  <input data-parsley-errors-messages-disabled type="text" name="first_name" id="first_name" class="form_MMD_F1" placeholder="<%%= t('form.placeholder.first_name') %>"  required="" data-parsley-required="" />
                </div>
                <div class="col-xs-12 form-input" id="error-last">
                  <input data-parsley-errors-messages-disabled type="text" name="last_name" id="last_name" class="form_MMD_F1" placeholder="<%%= t('form.placeholder.last_name') %>"  required="" data-parsley-required="" />
                </div>
              <% end %>
              <% if show_fields[:email] %>
                <div class="col-xs-12 form-input" id="error-email">
                  <input data-parsley-errors-messages-disabled type="email" name="email" id="email" class="form_MMD_F1" placeholder="<%%= t('form.placeholder.email') %>"  required="" data-parsley-required="" />
                </div>
              <% end %>
              <% if show_fields[:phone] %>
                <div class="col-xs-12 form-input" id="error-phone">
                  <input data-parsley-errors-messages-disabled type="tel" name="phone" id="phone" class="form_MMD_F1" placeholder="<%%= t('form.placeholder.phone') %>"  required="" data-parsley-required="" />
                </div>
              <% end %>

              <div class="clearfix"></div>

              <div class="saint-jean-cgu">
                <div class="col-xs-2">
                  <div class="cgu">
                    <input data-parsley-errors-messages-disabled type="checkbox" name="cgu" id="cgu" required=""  data-parsley-trigger="change"/>
                    <label for="cgu"></label>
                  </div>
                </div>
                <div class="col-xs-9">
                  <p class="text-cgu">
                    <%%= t('legal.full_disclaimer') %> <a href="#" id="link_cgu"><%%= t('legal.conditions') %></a>
                  </p>
                </div>
              </div>

              <div class="clearfix"></div>
              <div class="col-xs-10 col-xs-offset-1">
                <input id="MMD_formBtn" type="submit" class="MMD_F1" value="<%%= t('form.submit') %>" />
              </div>
            </div>
          </div>
        </div>
      </div>

      <%%= render 'splash/default_splash_fields' %>
    </form>

    <div id="MMD_conditions">
      <div id="MMD_conditionsHeader">
        <div class="MMD_conditionsTitre MMD_F1">Conditions Générales de Utilisation</div>
        <img id="MMD_conditionsCClick" class="MMD_conditionsClose" src="/assets/custom/shared/images/Close_btn.png" />
      </div>
      <div class="container">
        <div class="row">
          <div class="MMD_innerContent">
            <div class="MMD_conditionsTexte MMD_F1">
              <%%= render 'splash/ivizone_terms.fr' %>
            </div>
          </div>
        </div>
      </div>
    </div>


  <script type="text/javascript" src="/assets/custom/shared/javascript/intlTelInput.js"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      $("#phone").intlTelInput({
        initialCountry: 'fr',
        preferredCountries: ['fr'],
        utilsScript: "/assets/custom/shared/javascript/utils.js"
      });

      function getNum(){
        var intlNumber = $("#phone").intlTelInput("getNumber");
        return intlNumber;
      }
      $form = $('#ivizone-form');
      $submit = $('#MMD_formBtn');
      $submit.on('click',function(e){
        e.preventDefault();
        $('#phone').val(getNum());
        $form.submit();
      });

      $submit.on('touchend', function(e){
        e.preventDefault();
        $('#phone').val(getNum());
        $form.submit();
      });
    });
  </script>

  </body>
</html>

app/views/splash/pages/templates/sms_registration.html.haml.erb
!!! 5
%html(lang='#{I18n.locale}')
  %head
    = render 'shared/head'
  %body
    = stylesheet_link_tag 'application.css'
    = render 'splash/css/application'
    #spinner

    %div#main_content
      .container
        :css
          #logo {
            height: <%= logo_height %>px;
            width: <%= logo_width %>px;
            margin-top: 40px;
          }

          .submit-btn {
            margin-top: 10px;
            font-weight: 700;
            width: 100%;
            background-color: <%= registration_button_color %>;
            color: white;
          }

        :css
          .ivizone-form {
            width: 80%;
            margin: auto;
            margin-bottom: 20px;
          }

          .form-group {
            margin: 0;
            margin-bottom: 8px;
          }

          .parsley-error {
            color: #B94A48 !important;
            background-color: #F2DEDE !important;
            border: 1px solid #EED3D7 !important;
          }

        .welcome
          .row
            = image_tag  asset_data_uri('<%= logo_path %>'), class: 'img-responsive', id: 'logo'

          .row.welcome-message
            %p#message
              = t('form.instructions')
              %br #{t('form.or')} #{link_to t('form.facebook_alternative'), alt_page('facebook') }

          = form_tag meraki_sms_registration_path, class: 'ivizone-form', role: 'form', id: 'ivizone-form', data: {'parsley-validate': true, 'parsley-focus': 'none'} do
            <% if show_fields[:name] %>
            .form-group
              = label_tag 'last_name', t('form.labels.last_name')
              = text_field_tag 'last_name', nil, placeholder: t('form.placeholder.last_name'), class: 'form-control', data: {'parsley-errors-messages-disabled': true, 'parsley-required': true}

            .form-group
              = label_tag 'first_name', t('form.labels.first_name')
              = text_field_tag 'first_name', nil, placeholder: t('form.placeholder.first_name'), class: 'form-control', data: {'parsley-errors-messages-disabled': true, 'parsley-required': true}
            <% end %>

            <% if show_fields[:phone] %>
            .form-group
              = label_tag 'phone', t('form.labels.phone')
              = phone_field_tag 'phone', nil,  class: 'form-control', data: {'parsley-errors-messages-disabled': true, 'parsley-required': true}
            <% end %>

            <% if show_fields[:email] %>
            .form-group
              = label_tag 'email', t('form.labels.email')
              = email_field_tag 'email', nil, placeholder: t('form.placeholder.email'), class: 'form-control', data: {'parsley-errors-messages-disabled': true, 'parsley-required': true}
            <% end %>

            .form-group
              = check_box_tag 'cgu', nil, false, data: {'parsley-errors-messages-disabled': true, 'parsley-required': true}
              = label_tag 'cgu', t('legal.full_disclaimer') 
              #{link_to t('legal.conditions'), '#', :'data-toggle' => "modal", id: 'termsLink', class: 'loader', :'data-target' => '#termsModal'}

            = render 'splash/default_splash_fields'

            = button_tag t('form.submit'), class: 'btn submit-btn', id: 'form-submit'

          .row.center-text.terms-link
            = render 'splash/terms_link'

        = render 'splash/international_phone_formatter'

    = javascript_include_tag 'application.js'
    = content_for :custom_javascript

    :javascript
      var opts = {
        lines: 10, // The number of lines to draw
        length: 13, // The length of each line
        width: 6, // The line thickness
        radius: 10, // The radius of the inner circle
        corners: 1, // Corner roundness (0..1)
        rotate: 0, // The rotation offset
        direction: 1, // 1: clockwise, -1: counterclockwise
        color: '#fff', // #rgb or #rrggbb or array of colors
        speed: 1.5, // Rounds per second
        trail: 30, // Afterglow percentage
        shadow: false, // Whether to render a shadow
        hwaccel: false, // Whether to use hardware acceleration
        className: 'spinner', // The CSS class to assign to the spinner
        zIndex: 2e9, // The z-index (defaults to 2000000000)
        top: '50', // Top position relative to parent in px
        left: '50' // Left position relative to parent in px
      };

      target = document.getElementById('spinner');
      var spinner = new Spinner(opts).spin(target);

      $('#facebook-link').click(function(e){
        $('#spinner').show();
        mixpanel.track('Facebook clicked');
      });

      if (typeof(Parsley) !== "undefined") {
        Parsley.on('form:submit', function(event){
          $('#spinner').show();
          mixpanel.track('Standard Form Submitted');
          //Ivizone.logEvent({event: 'UserSubmittedForm'});
        });
      }

      mixpanel.register(#{@tracking_data.to_json.html_safe});
      mixpanel.track("Page loaded");
      mixpanel.track_links('#termsLink', "Viewed Terms");